version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install && npm run build
      - run: docker login -u kalbeee -p aaaa1234
      - run: docker build -t kalbeee/stock:latest .
      - run: docker push kalbeee/stock:latest

workflows:
  build-dep:
    jobs:
      - build
